---
title: "Research output"
---

## Recent publications

See also at [Google Scholar](https://scholar.google.ch/citations?user=uR1_O0UAAAAJ) and [Pubmed](https://pubmed.ncbi.nlm.nih.gov/?term=Schwab+Simon%5BAuthor%5D+AND+%28+Zurich%5BAffiliation%5D+OR+Bern%5BAffiliation%5D+OR+Warwick%5BAffiliation%5D+OR+Oxford%5BAffiliation%5D+%29&sort=date).

van Zwet, E., Gelman, A., Greenland, S., Imbens, G., **Schwab, S.**, & Goodman, S. N. (2023). A New Look at P Values for Randomized Clinical Trials. *NEJM Evidence*, EVIDoa2300003. [doi:10.1056/EVIDoa2300003](https://doi.org/10.1056/EVIDoa2300003)

**Schwab, S.**, & Immer, F. (2023). Prognosemodelle und künstliche Intelligenz. *SAEZ Schweizerische Ärztezeitung*. [doi:10.4414/saez.2023.1266894718](https://saez.swisshealthweb.ch/de/article/doi/saez.2023.1266894718/)

**Schwab, S.**, Sidler, D., Haidar, F., Kuhn, C., Schaub, S., Koller, M., Mellac, K., Stürzinger, U., Tischhauser, B., Binet, I., Golshayan, D., Müller, T., Elmer, A., Franscini, N., Krügel, N., Fehr, T., Immer, F., Swisstransplant Kidney Working Group (STAN), & Swiss Transplant Cohort Study. (2023). Clinical prediction model for prognosis in kidney transplant recipients (KIDMO): study protocol. *Diagnostic and Prognostic Research*, 7(1), 6. [doi:10.1186/s41512-022-00139-5](https://doi.org/10.1186/s41512-022-00139-5)

**Schwab, S.**, Janiaud, P., Dayan, M., Amrhein, V., Panczak, R., Palagi, P. M., Hemkens, L. G., Ramon, M., Rothen, N., Senn, S., Furrer, E., & Held, L. (2022). Ten simple rules for good research practice. *PLoS Computational Biology, 18(6)*, e1010139. [doi:10.1371/journal.pcbi.1010139](https://doi.org/10.1371/journal.pcbi.1010139)

## R Software
[EXAM](https://github.com/Swisstransplant/EXAM)---Ex vivo allograft monitoring dashboard.

[swt](https://github.com/Swisstransplant/swt)---Swisstransplant R package.

[cochrane](https://github.com/schw4b/cochrane)---Import Data from the Cochrane Database of Systematic Reviews (CDSR).

## Reproducibility Notes

A series of commentaries highlight topics related to the production of robust, effective and reproducible science, see also [here](https://www.crs.uzh.ch/en/resources/CRS-Reproducibility-Notes.html).

**Schwab, S.**, & Held, L. (2021). Statistical programming: Small mistakes, big impacts. *Significance, 18(3)*, 6–7. [doi:10.1111/1740-9713.01522](https://doi.org/10.1111/1740-9713.01522)

Held, L., Pawel, S., & **Schwab, S.** (2020). Replication power and regression to the mean. *Significance, 17(6)*, 10–11. [doi:10.1111/1740-9713.01462](https://doi.org/10.1111/1740-9713.01462)

**Schwab, S.**, & Held, L. (2020). Science after Covid-19: Faster, better, stronger? *Significance, 17(4)*, 8–9. [doi:10.1111/1740-9713.01415](https://doi.org/10.1111/1740-9713.01415)

**Schwab, S.**, & Held, L. (2020). Different worlds Confirmatory versus exploratory research. *Significance, 17(2)*, 8–9. [doi:10.1111/1740-9713.01369](https://doi.org/10.1111/1740-9713.01369)

Held, L., & **Schwab, S.** (2020). Improving the reproducibility of science. *Significance, 17(1)*, 10–11. [doi:10.1111/j.1740-9713.2020.01351.x](https://doi.org/10.1111/j.1740-9713.2020.01351.x)

## Presentations

A complete list with slides from [my presentations](https://osf.io/a3g5c/) are available at OSF.

[EXAM---Ex-vivo allograft monitoring dashboard for deceased-donor kidney transplantation](https://osf.io/8kbt2/) (see also [video](https://youtu.be/0cvZDnkeKPk?si=pp9PGFDCoy0L2AWh))\
Talk at R/Basel 2023---Roche\
*21/06/23*

[Understanding and managing bias in medical research](https://osf.io/yh76a/)\
Talk for the Swiss Society for Pneumology---University Hospital of Zurich\
*04/02/22 / 14/04/2023*

[An Introduction to R with the Stanford Heart Transplant data](https://osf.io/6mcah/)\
Talk at BernR---Bern R user group\
*09/12/21*

[From Regression to Machine Learning in R](https://osf.io/rua6x/) (see also [video](https://www.youtube.com/watch?v=h5A1v678Djk))\
Talk in the seminar *Applied Machine Learning in Diagnostic Imaging*---University Hospital of Zurich\
*15/04/21*

